2020-07-14T14:02:43.2367437+07:00  [ERR] Failed executing DbCommand ("309"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [AppCustomers] (
    [Id] int NOT NULL IDENTITY,
    [CreatedBy] nvarchar(256) NULL,
    [UpdatedBy] nvarchar(256) NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [Name] nvarchar(100) NOT NULL,
    [Email] nvarchar(100) NULL,
    [PhoneNumber] varchar(30) NULL,
    [Address] nvarchar(max) NULL,
    [City] nvarchar(50) NULL,
    [Gender] int NOT NULL,
    [DateCreated] datetime2 NOT NULL,
    [DateModified] datetime2 NOT NULL,
    CONSTRAINT [PK_AppCustomers] PRIMARY KEY ([Id])
);" (627a98df)
2020-07-14T14:02:44.6048816+07:00  [FTL] Error whilst creating and seeding database (944fb156)
System.AggregateException: One or more errors occurred. (There is already an object named 'AppCustomers' in the database.)
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AppCustomers' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at DAL.DatabaseInitializer.SeedAsync() in D:\QuickApp-STANDARD-v4.0.0\QuickApp-STANDARD-v4.0.0\kitchen-sink\QuickApp.Standard\DAL\DatabaseInitializer.cs:line 51
   at QuickApp.AppDbInitializer.SeedAsync() in D:\QuickApp-STANDARD-v4.0.0\QuickApp-STANDARD-v4.0.0\kitchen-sink\QuickApp.Standard\QuickApp\AppDbInitializer.cs:line 47
ClientConnectionId:92efcd3b-2b84-48c0-b7d4-d9aace03551c
Error Number:2714,State:6,Class:16
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at QuickApp.Program.Main(String[] args) in D:\QuickApp-STANDARD-v4.0.0\QuickApp-STANDARD-v4.0.0\kitchen-sink\QuickApp.Standard\QuickApp\Program.cs:line 35
